Repository GoBeromsu/Blind-Tok, pull requests merged in 2023-05, with the labels that each got.

#17 05.05 PR_추우엽
  frontend/package.json
  frontend/src/actions/types.js
  frontend/src/actions/user_action.js
  frontend/src/components/AudioPlayer.js
  frontend/src/components/BoxComponent.js
  frontend/src/components/MainComponent.js
  frontend/src/components/ResponsiveComponent.js
  frontend/src/components/style/Login.css
  frontend/src/components/views/App.js
  frontend/src/components/views/AudioPlayer.js
  frontend/src/components/views/BTlogo.js
  frontend/src/components/views/BoxComponent.js
  frontend/src/components/views/Br.js
  frontend/src/components/views/Button.js
  frontend/src/components/views/CircularImage.js
  frontend/src/components/views/FriendPage.js
  frontend/src/components/views/Header.js
  frontend/src/components/views/LandingPage.js
  frontend/src/components/views/MainComponent.js
  frontend/src/components/views/MessageBox.js
  frontend/src/components/views/RegisterPage.js
  frontend/src/components/views/ResponsiveComponent.js
  frontend/src/components/views/SideBar.js
  frontend/src/components/views/UserProfile.js
  frontend/src/components/views/VideoPlayer.js
  frontend/src/index.js
  frontend/src/reducers/index.js
  frontend/src/reducers/user_reducer.js
  frontend/src/store/index.js
Labels: Status: InProgress, Priority: Medium

#26 구글 로그인 버튼 생성 및 잡다한 에러 삭제
  backend/src/index.ts
  backend/yarn.lock
  frontend/package.json
  frontend/public/manifest.json
  frontend/src/actions/types.js
  frontend/src/actions/user_action.js
  frontend/src/components/views/App.js
  frontend/src/components/views/BTlogo.js
  frontend/src/components/views/GoogleLoginBtn.js
  frontend/src/components/views/RegisterPage.js
  frontend/src/components/views/SideBar.js
  frontend/src/index.js
  frontend/src/reducers/index.js
  frontend/src/reducers/user_reducer.js
  frontend/src/store/index.js
Labels: Status : Available, Status : Done, Priority: Medium

#27 Choi
  frontend/src/components/style/AudioPlayer.css
  frontend/src/components/style/ChatList.css
  frontend/src/components/style/FriendList.css
  frontend/src/components/style/SideBar.css
  frontend/src/components/views/App.js
  frontend/src/components/views/AudioPlayer.js
  frontend/src/components/views/ChatList.js
  frontend/src/components/views/ChatRoom.js
  frontend/src/components/views/FriendList.js
  frontend/src/components/views/FriendPage.js
  frontend/src/components/views/MessageBox.js
  frontend/src/components/views/SideBar.js
  frontend/src/data/chat_data.js
  frontend/src/data/chat_list.js
  frontend/src/data/friend_data.js
  frontend/src/data/user_data.js
Labels: Type : Enhancement, Status : Available

#29 FE: 디렉터리 구조 정리
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/style/AudioPlayer.css
  frontend/src/components/views/Chat/BoxComponent.jsx
  frontend/src/components/views/Chat/ChatList.jsx
  frontend/src/components/views/Chat/ChatRoom.jsx
  frontend/src/components/views/Friend/FriendList.jsx
  frontend/src/components/views/Friend/FriendPage.jsx
  frontend/src/components/views/Header.js
  frontend/src/components/views/LandingPage.js
  frontend/src/components/views/Layout/Br.js
  frontend/src/components/views/Layout/Button.js
  frontend/src/components/views/Layout/CircularImage.jsx
  frontend/src/components/views/Layout/SideBar.jsx
  frontend/src/components/views/Login/GoogleLoginBtn.js
  frontend/src/components/views/Login/LoginPage.jsx
  frontend/src/components/views/Login/kOauth.jsx
  frontend/src/components/views/MainPage/AudioPlayer.jsx
  frontend/src/components/views/MainPage/MainComponent.jsx
  frontend/src/components/views/MainPage/MessageBox.jsx
  frontend/src/components/views/MainPage/ResponsiveComponent.jsx
  frontend/src/components/views/MainPage/VideoPlayer.jsx
  frontend/src/components/views/User/UserProfile.jsx
  frontend/src/data/chat_list.js
  frontend/src/image/BTlogo.jsx
  frontend/src/image/defaultImage.png
  frontend/src/index.jsx
Labels: Status : Available, Status : Done, Priority: High

#61 유저의 오디오 리스트 조회
  backend/yarn.lock
  frontend/src/App.tsx
  frontend/src/components/style/App.css
  frontend/src/components/views/MainPage/AudioUpload.tsx
  frontend/src/data/upload/axios.tsx
  frontend/src/data/upload/query.tsx
  frontend/src/data/upload/state.tsx
Labels: Status: InProgress, Status : Available, Priority: Medium

#66 이제 File upload 하면 user의 AudioList 리랜더링됨.
  frontend/src/components/views/MainPage/AudioUpload.tsx
  frontend/src/data/constant.tsx
  frontend/src/data/upload/axios.tsx
  frontend/src/data/upload/query.tsx
Labels: Type : Enhancement, Status : Done, Priority: Medium
